name: StockholmTreeQuest
options:
  bundleIdPrefix: com.chernega
settings:
  base:
    SWIFT_VERSION: 6.0
    IPHONEOS_DEPLOYMENT_TARGET: 18.0
    SUPPORTED_PLATFORMS: iphoneos iphonesimulator
targets:
  StockholmTreeQuest:
    type: application
    platform: iOS
    deploymentTarget: '18.0'
    sources:
      - path: Sources
      - path: Resources/Assets.xcassets
        type: folder.assetcatalog
        buildPhase: resources
      - path: Resources/Localization
        type: folder
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.chernega.StockholmTreeQuest
        DEVELOPMENT_TEAM: ""
        SWIFT_VERSION: 6.0
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        IPHONEOS_DEPLOYMENT_TARGET: 18.0
        SUPPORTED_PLATFORMS: iphoneos iphonesimulator
        TARGETED_DEVICE_FAMILY: 1
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Мы используем вашу геолокацию, чтобы отмечать местоположение рождественских ёлок поблизости."
        INFOPLIST_KEY_NSLocationAlwaysAndWhenInUseUsageDescription: "Геолокация помогает отображать найденные ёлки даже после возврата в приложение."
        INFOPLIST_KEY_CFBundleDisplayName: "Tree Quest"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
  StockholmTreeQuestTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: '18.0'
    sources:
      - path: Tests/StockholmTreeQuestTests
    dependencies:
      - target: StockholmTreeQuest
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
schemes:
  StockholmTreeQuest:
    build:
      targets:
        StockholmTreeQuest: all
        StockholmTreeQuestTests: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - StockholmTreeQuestTests
